export const Films =[
    {id: 1,
         name: ' Giratina & the Sky Warrior (2008)', 
         type: 'Cartoon', 
         img: 'assets/img/mv1.jpg',
         info: 'When a new Pokèmon emerges able to create parallel dimensions, its up to Ash Ketchum and his friends to stop a mysterious stranger from using its powers for evil',
         clip: 'https://www.youtube.com/embed/7DliP7EX9To'
        },
    {id: 2, 
        name: 'Arceus and the Jewel of Life (2009)', 
         type: 'Cartoon', 
         img:'assets/img/mv2.jpg',
         info:'Arceus, creator of the world, comes to pass judgement on humanity for the theft of the Jewel of Life, but Ash Ketchum and his friends are sent back in time to discover and possible reverse the events that led to Arceus vendetta.',
         clip: 'https://www.youtube.com/embed/u0uW_J5enjU'
        },
    {id: 3, 
        name: 'Zoroark - Master of Illusions (2010)', 
        type: 'Cartoon', 
        img:'assets/img/mv3.jpg',
        info:'A greedy, manipulative media mogul seeks to capture Celebi for nefarious purposes, using the shape-shifting Pokémon Zoroark to hunt it down.',
        clip:'https://www.youtube.com/embed/3Iy3UlYdF9U'
    },
    {id: 4, 
        name: 'Victini And Zekrom (2011)',  
        type: 'Cartoon',
        img:'assets/img/mv4.jpg',
        info:'Damon plans to trap Victini and harness its power, and as that plan gets under way, the entire town of Eindoak faces disaster! Will the power of Ash’s ideals convince the Legendary Pokémon Zekrom to help stop Damon? Can they rescue Victini? The greatest adventure in Pokémon history approaches!',
        clip:'https://www.youtube.com/embed/sgpqZq8KG8U'
    },
    {id: 5, 
        name: 'Kyurem vs. the Sword of Justice (2012) ', 
        type: 'Cartoon',
        img:'assets/img/mv5.jpg',
        info:'Ash and friends are attacked by the legendary dragon-like Kyurem, but fight it off and help an injured Pokemon. They learn its on its way to rescue its friends from Kyurems icy clutches and help.',
        clip: 'https://www.youtube.com/embed/Zmd_uEHxO0Q'
    },
    {id: 6, 
        name: 'Genesect and the Legend Awakened (2013)', 
        type: 'Cartoon', 
        img:'assets/img/mv6.jpg',
        info: 'When big trouble threatens the big city, its up to Ash, Pikachu, and their friends to stop it. A vast Pokémon habitat amid the hustle and bustle of the big city quickly becomes a problem when the nest threatens the citys power.',
        clip: 'https://www.youtube.com/embed/Thjcman-1S0'
    },
    {id: 7, 
        name: ' Diancie and the Cocoon of Destruction (2014)', 
         type: 'Cartoon',
          img:'assets/img/mv7.jpg',
          info:'Feature length film about the adventures of Ash Ketchum and his friends. In a country called Diamond Domain lies the powerful Heart Diamond which has served as the kingdoms source of energy and maintained it for centuries. Many Carbink live in Diamond Domain, including their princess - the Jewel Pokemon Diancie, who created the Heart Diamond. Diancie no longer has the power to control the Heart Diamond and her country is falling into chaos as a result.',
          clip:'https://www.youtube.com/embed/LJsUpbA-Uys'
        },
    {id: 8, 
        name: 'Hoopa and the Clash of Ages (2015)',  
        type: 'Cartoon', 
        img:'assets/img/mv8.jpg',
        info:'When Ash, Pikachu, and their friends visit a desert city by the sea, they meet the Mythical Pokemon Hoopa, who is able to summon things - including people and Pokemon - through its magic ring. After a scary incident, they learn a story about a brave hero who stopped the rampage of a terrifying Pokemon long ago. Now, that Pokemon is in danger of breaking loose again! Can Ash help overcome the darkness within - or will a dangerous secret erupt into a clash of legends?',
        clip:'https://www.youtube.com/embed/GChQk8ixeYc'
    },
    {id: 9, 
        name: 'Volcanion and the Mechanical Marvel (2016)', 
         type: 'Cartoon',
          img:'assets/img/mv9.jpg',
          info:'Ash meets the mythical Pokémon Volcanion when it crashes down from the sky, and a mysterious force binds the two of them together. Volcanion despises humans and tries to get away, but its forced to drag Ash along as it continues its rescue mission.',
          clip:'https://www.youtube.com/embed/z64EWoVbLPI'
        }
];